** compile error work around **
error message:

rtp/h261_play.cpp:62:19: error: osfcn.h: No such file or directory
make: *** [rtp/h261_play.o] Error 1


therefore, commented out "osfcn.h" inclusion.